"""
EfficientNet-B4 CNN Style Classifier.

Binary classifier that determines whether an image was generated by AI
based on learned style patterns and artefact fingerprints.  Uses
EfficientNet-B4 (via timm) as backbone with a custom classification head.

This detector learns "style signatures" unique to specific AI generators,
providing detection even when watermarks have been removed.

Architecture:
    EfficientNet-B4 (pretrained) → Global Avg Pool → MLP → sigmoid

References:
    - EfficientNet (Tan & Le, 2019)
    - CNNDetection (Wang et al., 2020)
"""

import logging
from typing import Tuple, Optional

import numpy as np

logger = logging.getLogger(__name__)

try:
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
except ImportError:
    raise ImportError("PyTorch required: pip install torch")

try:
    import timm
except ImportError:
    timm = None

try:
    import cv2
except ImportError:
    cv2 = None


class CNNClassifier:
    """EfficientNet-B4 AI image classifier.

    Provides a binary AI-generated vs. natural image classifier.
    Wraps model loading, preprocessing, and inference into a clean API.

    Args:
        model_path: Path to trained model weights (optional).
        device: Torch device ("cuda" or "cpu").
        threshold: Classification threshold (default 0.5).

    Example:
        >>> classifier = CNNClassifier()
        >>> image = cv2.imread("test.png")
        >>> is_ai, confidence = classifier.predict(image)
        >>> print(f"AI-generated: {is_ai} ({confidence:.2%})")
    """

    def __init__(
        self,
        model_path: Optional[str] = None,
        device: Optional[str] = None,
        threshold: float = 0.5,
    ):
        self.device = torch.device(
            device or ("cuda" if torch.cuda.is_available() else "cpu")
        )
        self.threshold = threshold
        self.image_size = 380  # EfficientNet-B4 default

        # Build model
        self.model = self._build_model()
        self.model = self.model.to(self.device)

        # Load weights if provided
        if model_path is not None:
            self._load_weights(model_path)

        self.model.eval()

        logger.info(
            f"CNNClassifier initialised: device={self.device}, "
            f"threshold={threshold}"
        )

    def _build_model(self) -> nn.Module:
        """Build EfficientNet-B4 binary classifier."""
        if timm is not None:
            model = timm.create_model(
                "efficientnet_b4",
                pretrained=True,
                num_classes=1,  # Binary classification
            )
        else:
            # Lightweight fallback
            model = nn.Sequential(
                nn.Conv2d(3, 32, 3, stride=2, padding=1),
                nn.BatchNorm2d(32),
                nn.ReLU(),
                nn.AdaptiveAvgPool2d(1),
                nn.Flatten(),
                nn.Linear(32, 1),
            )
            logger.warning("timm not available; using lightweight fallback CNN")

        return model

    def _load_weights(self, path: str):
        """Load trained model weights."""
        try:
            state_dict = torch.load(path, map_location=self.device)
            if "model_state" in state_dict:
                state_dict = state_dict["model_state"]
            self.model.load_state_dict(state_dict)
            logger.info(f"Loaded weights from {path}")
        except Exception as e:
            logger.warning(f"Could not load weights from {path}: {e}")

    def _preprocess(self, image: np.ndarray) -> torch.Tensor:
        """Preprocess image for model input.

        Args:
            image: BGR numpy image (H, W, 3).

        Returns:
            Normalised tensor (1, 3, H, W).
        """
        # Resize
        if cv2 is not None:
            img = cv2.resize(image, (self.image_size, self.image_size))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        else:
            from PIL import Image
            import io
            # Fallback
            img = np.array(Image.fromarray(image).resize(
                (self.image_size, self.image_size)
            ))

        # Normalise to [0, 1] then apply ImageNet stats
        tensor = torch.tensor(img, dtype=torch.float32).permute(2, 0, 1) / 255.0
        mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
        std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
        tensor = (tensor - mean) / std

        return tensor.unsqueeze(0).to(self.device)

    @torch.no_grad()
    def predict(self, image: np.ndarray) -> Tuple[bool, float]:
        """Classify whether an image is AI-generated.

        Args:
            image: Input image (BGR numpy array, H×W×3).

        Returns:
            Tuple of (is_ai_generated, confidence).
            ``confidence`` is in [0, 1]; higher means more likely AI-generated.
        """
        self.model.eval()
        tensor = self._preprocess(image)
        logit = self.model(tensor)
        confidence = torch.sigmoid(logit).item()
        is_ai = confidence >= self.threshold

        logger.debug(f"CNN classification: ai={is_ai}, conf={confidence:.3f}")
        return is_ai, confidence

    @torch.no_grad()
    def predict_batch(
        self, images: list
    ) -> list:
        """Classify a batch of images.

        Args:
            images: List of BGR numpy images.

        Returns:
            List of (is_ai, confidence) tuples.
        """
        self.model.eval()
        tensors = torch.cat([self._preprocess(img) for img in images], dim=0)
        logits = self.model(tensors)
        confidences = torch.sigmoid(logits).squeeze().cpu().numpy()

        if confidences.ndim == 0:
            confidences = [float(confidences)]
        else:
            confidences = confidences.tolist()

        return [(c >= self.threshold, c) for c in confidences]

    def get_model(self) -> nn.Module:
        """Get the underlying PyTorch model (for training)."""
        return self.model
